# Generated by Django 3.0.5 on 2020-04-20 17:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('article_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('python', models.BooleanField()),
                ('django', models.BooleanField()),
                ('technologies', models.ManyToManyField(related_name='projects', to='article_one.Technology')),
            ],
        ),
    ]
