# Generated by Django 3.0.5 on 2020-04-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_one', '0003_auto_20200420_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resposibility',
            new_name='Responsibility',
        ),
    ]
