# Generated by Django 3.0.5 on 2020-04-24 17:04

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('article_one', '0004_auto_20200420_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontent',
            name='article_one_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 17, 4, 7, 12909)),
        ),
    ]
