# Generated by Django 3.0.5 on 2020-04-24 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_one', '0005_articlecontent_article_one_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibility',
            name='project',
        ),
        migrations.AlterField(
            model_name='articlecontent',
            name='article_one_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 18, 30, 41, 612647)),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Responsibility',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
