# Generated by Django 3.0.5 on 2020-04-24 18:37

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('article_one', '0006_auto_20200424_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='article_one_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 18, 37, 55, 1220)),
        ),
    ]
