# Generated by Django 3.0.5 on 2020-05-02 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_one', '0010_auto_20200502_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='article_one_time',
            field=models.DateField(default=datetime.datetime(2020, 5, 2, 20, 43, 12, 363338)),
        ),
    ]
