# Generated by Django 3.0.5 on 2020-04-27 17:57

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('article_one', '0010_auto_20200427_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='article_one_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 17, 57, 44, 720918)),
        ),
    ]
