# Generated by Django 3.0.5 on 2020-05-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_one', '0011_auto_20200502_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleContent',
        ),
    ]
