# Generated by Django 3.0.5 on 2020-05-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_one', '0011_auto_20200427_2057'),
        ('article_one', '0012_delete_articlecontent'),
    ]

    operations = [
    ]
