# Generated by Django 3.0.5 on 2020-04-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_two', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecontent',
            old_name='articlecontent',
            new_name='article_two_content',
        ),
    ]
