# Generated by Django 3.0.5 on 2020-04-24 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_two', '0002_auto_20200419_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontent',
            name='article_one_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 18, 30, 41, 614645)),
        ),
    ]
