# Generated by Django 3.0.5 on 2020-04-24 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_two', '0003_articlecontent_article_one_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontent',
            name='article_one_time',
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='article_two_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 18, 37, 55, 3222)),
        ),
    ]
