# Generated by Django 3.0.5 on 2020-04-25 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_two', '0004_auto_20200424_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='article_two_time',
            field=models.DateField(default=datetime.datetime(2020, 4, 25, 9, 10, 52, 448873)),
        ),
    ]
