# Generated by Django 3.0.5 on 2020-05-02 19:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200419_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepreview',
            name='article_1',
        ),
        migrations.RemoveField(
            model_name='articlepreview',
            name='article_2',
        ),
        migrations.AddField(
            model_name='articlepreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
