# Generated by Django 3.0.5 on 2020-05-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200502_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepreview',
            old_name='article',
            new_name='article_text',
        ),
        migrations.AddField(
            model_name='articlepreview',
            name='article_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articlepreview',
            name='article_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
