# Generated by Django 3.0.5 on 2020-05-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200502_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepreview',
            options={'verbose_name_plural': 'Article'},
        ),
    ]
